// Generated by npm run sync:public-reason-codes. Do not edit by hand.
export interface PublicReasonCodeReading {
  title: string;
  detail: string;
}

export const PUBLIC_REASON_CODE_READINGS: Record<string, PublicReasonCodeReading> = {
  BACKTEST_NOT_RUN: {
    "title": "尚未运行对齐回测",
    "detail": "没有与当前策略对齐的回测产物；策略结论保持阻断。"
  },
  CALIBRATION_NOT_IMPLEMENTED: {
    "title": "校准与模型提升尚未实现",
    "detail": "排序尚未经过 walk-forward 校准，只能作为研究观察，不能作为收益预测。"
  },
  DATA_TRUST_OBSERVATION_COLLECTING: {
    "title": "数据可信度仍在积累",
    "detail": "连续观测尚未达到提升门槛；不会提前宣称数据源已受信任。"
  },
  DATA_TRUST_THRESHOLD_EVIDENCE_MISSING: {
    "title": "可信提升门槛无法验证",
    "detail": "报告缺少可信提升所需的门槛证据；页面保持保守状态，不把该数据源标记为可信。"
  },
  DTE_EVIDENCE_CONFLICT: {
    "title": "候选期限证据无法验证",
    "detail": "候选的 DTE 与到期日证据冲突或损坏；公开产物已隐藏该候选，而不是猜测期限。"
  },
  EVENTS_FEED_MALFORMED: {
    "title": "交易所事件源格式异常",
    "detail": "Deribit public/status 响应格式异常；页面拒绝从异常数据推断锁定状态。"
  },
  EVENTS_FEED_STALE: {
    "title": "交易所事件源已过期",
    "detail": "Deribit public/status 的观察时间超过新鲜度上限；旧状态不能继续作为当前证据。"
  },
  EVENTS_MISSING: {
    "title": "交易所事件源缺失",
    "detail": "报告没有拿到 Deribit public/status 的交易所锁定状态；缺失不会被解释成 0。"
  },
  EVENT_SCORE_NOT_EXCHANGE_LOCK_STATE: {
    "title": "事件分不符合公开契约",
    "detail": "事件分不是公开契约允许的 0、0.80 或 1.00；页面拒绝猜测其含义并保持阻断。"
  },
  EVENT_SOURCE_UNAVAILABLE: {
    "title": "交易所事件证据不可用",
    "detail": "公开事件来源、范围或新鲜度无法验证；事件门保持阻断，缺失值不会显示为 0。"
  },
  EXCHANGE_FULL_LOCK: {
    "title": "交易所处于全局锁定",
    "detail": "Deribit public/status 报告全交易所锁定；事件分为 1.00，研究门按阻断处理。"
  },
  EXCHANGE_LOCK_STATE_UNAVAILABLE: {
    "title": "交易所锁定状态不可用",
    "detail": "公开事件源存在，但没有可验证的锁定分；在状态明确前按阻断处理。"
  },
  EXCHANGE_NO_ACTIVE_LOCKS: {
    "title": "交易所未报告锁定",
    "detail": "当次 Deribit public/status 未报告交易所、币种或指数锁定。该源不包含宏观事件日历。"
  },
  EXCHANGE_PARTIAL_LOCK: {
    "title": "交易所存在部分锁定",
    "detail": "Deribit public/status 报告币种或指数锁定；事件分为 0.80，研究门按阻断处理。"
  },
  INSUFFICIENT_VRP_HISTORY: {
    "title": "VRP 样本不足",
    "detail": "VRP 有效读数少于报告声明的最低样本数，头条数字保持不可用。"
  },
  MARKET_DATA_AGE_EXCEEDED: {
    "title": "市场快照已经过期",
    "detail": "快照超过报告的新鲜度上限；旧报价不会继续充当当前市场证据。"
  },
  MARKET_DATA_QUALITY_FAIL: {
    "title": "市场快照未通过质量门禁",
    "detail": "公开快照未通过质量门禁；价格、波动率和事件状态不会从失败数据中推断。"
  },
  MARKET_TRUST_THRESHOLD_EVIDENCE_MISSING: {
    "title": "市场可信门槛无法复核",
    "detail": "可信状态缺少门槛元数据，页面不会把它解释为已验证的数据源。"
  },
  MISSING_DVOL_HISTORY: {
    "title": "缺少 DVOL 历史",
    "detail": "VRP 需要连续 DVOL 历史；缺失值不会显示成 0。"
  },
  MISSING_VALIDATED_MARKET_DATA: {
    "title": "没有可验证的市场快照",
    "detail": "公开报告没有通过质量门禁的行情；价格、波动率和候选都不会被估算或补齐。"
  },
  MISSING_VALIDATED_PATH_RISK: {
    "title": "缺少已验证的路径风险证据",
    "detail": "历史路径证据不足；页面不会把相对排序伪装成绝对预期价值。"
  },
  NO_ELIGIBLE_CANDIDATES: {
    "title": "本次没有合格研究候选",
    "detail": "没有合约同时满足期限、delta、报价、流动性和信用门槛；这不是故障。"
  },
  NO_OPEN_POSITIONS: {
    "title": "没有可评估的持仓",
    "detail": "公开研究不接入私人持仓；本项只是明确的空状态。"
  },
  NO_VALIDATED_PATH_RISK: {
    "title": "候选缺少路径风险证据",
    "detail": "该候选没有足够的持有期历史或未进入计算配额，因此不发布 EV。"
  },
  PUBLISHED_EDITION_STALE: {
    "title": "公开版已超过发布时效",
    "detail": "这份公开报告已超过展示时效；当前市场数字与事件状态均按阻断处理。"
  },
  REGIME_MIN_OBSERVATIONS_NOT_MET: {
    "title": "市场状态观测数不足",
    "detail": "有效观测未达到预设下限，结论保持不可用。"
  },
  REGIME_ROLLING_FIELDS_INCOMPLETE: {
    "title": "市场状态字段不完整",
    "detail": "滚动状态所需字段存在缺口；页面不会用默认值补齐。"
  },
  REGIME_ROLLING_HISTORY_INSUFFICIENT: {
    "title": "市场状态历史不足",
    "detail": "滚动历史不足以验证市场状态，权限保持为零。"
  },
  REGIME_TRUST_EVIDENCE_NOT_PROMOTED: {
    "title": "市场状态证据尚未提升",
    "detail": "状态证据仍是研究级，不能用于放开任何执行权限。"
  },
  SURFACE_QUALITY_FAIL: {
    "title": "波动率曲面未通过质量检查",
    "detail": "拟合或无套利检查失败；页面不会把拟合误差报告成优势。"
  },
  TRUST_EVIDENCE_NOT_OBSERVED: {
    "title": "数据可信度尚未形成观测证据",
    "detail": "还没有足够的连续采集证据证明数据链稳定，页面保持保守状态。"
  },
  TRUST_PROMOTION_MINIMUMS_MISSING: {
    "title": "可信提升最低门槛缺失",
    "detail": "可信证据不完整，不能验证是否达到 6 次连续通过与 60 秒观察要求。"
  },
  UNCALIBRATED_SCORE_MODEL: {
    "title": "打分模型未校准",
    "detail": "分数只衡量相对定价，不代表盈利概率。"
  },
};
