import { webcrypto } from 'node:crypto';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { EMPTY_DEFAULTS, normalizeCsv, parseCsv, quoteGroups, sourceFromCsv, suggestMapping, type QuoteSource } from './csv';
import { candidateFailure, discover, initialCriteria, makeCandidate } from './engine';
import { appendPlanEvent, createPlan, importPlan, loadPlans, persistPlans, PLAN_STORAGE_KEY, recheckPlan } from './plans';
import { sampleCsv } from './samples';
import { isoInstant } from './time';

beforeEach(()=>{localStorage.clear();vi.stubGlobal('crypto',webcrypto);});
const source=async(version:'a'|'b'|'bad'='a')=>{const text=sampleCsv(version),table=parseCsv(text);return sourceFromCsv(text,`合成-${version}.csv`,table,suggestMapping(table.headers),EMPTY_DEFAULTS,true);};
const analysis=async()=>{const s=await source();const criteria=initialCriteria(s);const result=discover(s,criteria);return {s,criteria,result,candidate:result.candidates.find(c=>c.long.bidSize!==null&&c.short.askSize!==null)!};};

describe('user quote normalization and actual filtering',()=>{
 it('accepts multiple expiries as independent groups and keeps sample provenance',async()=>{const s=await source();expect(s.rows).toHaveLength(40);expect(quoteGroups(s)).toHaveLength(4);expect(s.synthetic).toBe(true);expect(s.id).toHaveLength(64);});
 it('parses quoted commas/newlines, BOM and exact source line numbers',()=>{const t=parseCsv('\uFEFFa,b\n"a,b","x\ny"\nq,z\n');expect(t.rows[0]).toEqual({line:2,values:['a,b','x\ny']});expect(t.rows[1].line).toBe(4);expect(()=>parseCsv('a,a\nx,y')).toThrow();expect(()=>parseCsv('a,b\n"no,x')).toThrow();});
 it('rejects impossible/calendar and timezone-ambiguous dates',()=>{expect(isoInstant('2026-02-30T08:00:00Z')).toBeNull();expect(isoInstant('2026-10-01 08:00:00')).toBeNull();expect(isoInstant('2026-10-01T25:00:00Z')).toBeNull();expect(isoInstant('2026-10-01T16:00:00+08:00')).toBe('2026-10-01T08:00:00.000Z');});
 it('locates bad rows and rejects all duplicate IDs rather than choosing one',async()=>{const s=await source('bad');expect(s.issues.map(i=>i.code)).toEqual(expect.arrayContaining(['QUOTE','UNIT','DEFINITION','TIME','DUPLICATE_ID']));expect(s.rows).toHaveLength(35);expect(s.issues.filter(i=>i.code==='DUPLICATE_ID')).toHaveLength(2);});
 it('normalizes per-contract quote units exactly once',async()=>{const a=await source();const text=sampleCsv().split('\n').map((line,i)=>{if(!i||!line)return line;const c=line.split(',');c[5]=String(Number(c[5])*Number(c[9]));c[6]=String(Number(c[6])*Number(c[9]));c[10]='per_contract';return c.join(',');}).join('\n');const table=parseCsv(text),b=normalizeCsv(table,suggestMapping(table.headers),EMPTY_DEFAULTS);expect(b.rows.map(r=>[r.bid,r.ask])).toEqual(a.rows.map(r=>[r.bid,r.ask]));});
 it('rejects off-tick quotes without silently rounding user data',()=>{const lines=sampleCsv().split('\n');const cells=lines[1].split(',');cells[5]='250.005';lines[1]=cells.join(',');const table=parseCsv(lines.join('\n'));const result=normalizeCsv(table,suggestMapping(table.headers),EMPTY_DEFAULTS);expect(result.issues[0].code).toBe('TICK');expect(result.rows.some(row=>row.row===2)).toBe(false);});
 it('changes candidates and exact risk when a quote changes, and really applies risk constraints',async()=>{const {s,criteria,result,candidate}=await analysis();expect(result.candidates.length).toBeGreaterThan(2);const altered=structuredClone(s);const row=altered.rows.find(r=>r.instrument===candidate.short.instrument)!;row.bid+=50;row.rawBid+=50;row.ask+=50;row.rawAsk+=50;const next=discover(altered,criteria).candidates.find(c=>c.id===candidate.id)!;expect(next.netCredit).not.toBe(candidate.netCredit);expect(next.profile.maxLoss).not.toBe(candidate.profile.maxLoss);expect(discover(s,{...criteria,maxLoss:1}).candidates).toHaveLength(0);expect(discover(s,{...criteria,maxLoss:1}).excluded.LOSS_LIMIT).toBeGreaterThan(0);});
 it('uses collision-free exact-leg identities even when instruments contain delimiters',async()=>{const s=await source();const puts=s.rows.filter(row=>row.asset==='BTC'&&row.optionType==='put'&&row.expiry.startsWith('2026-10-22')).slice(0,4);const names=['A','A::B','B::C','C'];puts.forEach((row,i)=>row.instrument=names[i]);const selected={...s,rows:puts};const result=discover(selected,{...initialCriteria(selected),maxLoss:100000});expect(new Set(result.candidates.map(c=>c.id)).size).toBe(result.candidates.length);expect(result.candidates.find(c=>c.long.instrument==='A'&&c.short.instrument==='B::C')!.id).not.toBe(result.candidates.find(c=>c.long.instrument==='A::B'&&c.short.instrument==='C')!.id);});
 it('uses known opening-side depth and rejects mismatched units within a candidate',async()=>{const {criteria,candidate}=await analysis();const low=makeCandidate({...candidate.long,askSize:0},candidate.short,criteria);expect(candidateFailure(low,criteria)).toBe('CAPACITY');expect(()=>makeCandidate({...candidate.long,multiplier:3},candidate.short,criteria)).toThrow();expect(()=>makeCandidate(candidate.long,candidate.short,{...criteria,currency:'USD'})).toThrow();});
});

describe('frozen plans and exact follow-up evidence',()=>{
 it('freezes original evidence, matches exact new legs and appends instead of overwriting',async()=>{const {s,criteria,candidate}=await analysis();const plan=createPlan(s,candidate,criteria,'先核对成本');const frozen=JSON.stringify(plan);const review=recheckPlan(plan,await source('b'));expect(review.status).toBe('matched');expect(review.newCandidate!.id).toBe(candidate.id);const next=appendPlanEvent(plan,'continue','新价差仍在条件内',review);expect(JSON.stringify(plan)).toBe(frozen);expect(next.events).toHaveLength(1);expect(importPlan(JSON.stringify(next))).toEqual(next);});
 it('never substitutes a missing leg and blocks older or unit-changed evidence',async()=>{const {s,criteria,candidate}=await analysis();const plan=createPlan(s,candidate,criteria,'固定腿');const b=await source('b');const missing={...b,rows:b.rows.filter(row=>row.instrument!==candidate.short.instrument)};expect(recheckPlan(plan,missing).status).toBe('blocked');const altered=structuredClone(b);altered.rows.find(row=>row.instrument===candidate.long.instrument)!.multiplier=99;expect(recheckPlan(plan,altered).status).toBe('blocked');expect(recheckPlan(plan,s).status).toBe('blocked');const next=appendPlanEvent(plan,'continue','保存新报价',recheckPlan(plan,b));expect(recheckPlan(next,b).status).toBe('blocked');});
 it('checks close-side depth separately and labels unknown close capacity',async()=>{const {s,criteria,candidate}=await analysis();const plan=createPlan(s,candidate,criteria,'核对平仓方向');const b=await source('b');b.rows.find(row=>row.instrument===candidate.long.instrument)!.bidSize=0;b.rows.find(row=>row.instrument===candidate.short.instrument)!.askSize=0;const blockedClose=recheckPlan(plan,b);expect(blockedClose.status).toBe('matched');expect(blockedClose.closeCapacity).toBe('insufficient');expect(blockedClose.closeReference).toBeNull();expect(blockedClose.referenceChange).toBeNull();b.rows.find(row=>row.instrument===candidate.long.instrument)!.bidSize=null;b.rows.find(row=>row.instrument===candidate.short.instrument)!.askSize=null;expect(recheckPlan(plan,b).closeCapacity).toBe('unknown');});
 it('recomputes imported derived fields and rejects incompatible contracts, source relabeling and fees',async()=>{const {s,criteria,candidate}=await analysis();const plan=createPlan(s,candidate,criteria,'原始判断');const reviewed=appendPlanEvent(plan,'continue','新证据',recheckPlan(plan,await source('b')));const tampered=structuredClone(reviewed);tampered.events[0].review!.newCandidate!.profile.maxLoss=-999999;tampered.events[0].review!.closeReference=999999;const clean=importPlan(JSON.stringify(tampered));expect(clean.events[0].review!.newCandidate!.profile.maxLoss).toBe(reviewed.events[0].review!.newCandidate!.profile.maxLoss);expect(clean.events[0].review!.closeReference).toBe(reviewed.events[0].review!.closeReference);for(const mutate of [(p:typeof plan)=>{p.criteria.entryFee=-1;},(p:typeof plan)=>{p.long.currency='USD';},(p:typeof plan)=>{p.source.synthetic=false;},(p:typeof plan)=>{p.long.quantity=-10;}] as ((p:any)=>void)[]){const p:any=structuredClone(plan);mutate(p);if('quantity'in p.long)expect(importPlan(JSON.stringify(p)).long).not.toHaveProperty('quantity');else expect(()=>importPlan(JSON.stringify(p))).toThrow();}});
 it('rejects frozen criteria that could never admit the original candidate',async()=>{const {s,criteria,candidate}=await analysis();const plan=createPlan(s,candidate,criteria,'可复核原记录');for(const patch of [{maxLoss:1},{asOf:'2026-10-01T14:00:00Z'}]){const altered=structuredClone(plan);Object.assign(altered.criteria,patch);expect(()=>importPlan(JSON.stringify(altered))).toThrow(/基准计划/);}const arb=structuredClone(plan);arb.short.bid=arb.short.rawBid=999999;arb.short.ask=arb.short.rawAsk=1000000;expect(()=>importPlan(JSON.stringify(arb))).toThrow(/基准计划/);});
 it('rejects a write above the read limit without poisoning saved plans',async()=>{const {s,criteria,candidate}=await analysis();const plan=createPlan(s,candidate,criteria,'保持可读取');const empty=loadPlans().state;const saved=persistPlans(empty,[plan]);const original=localStorage.getItem(PLAN_STORAGE_KEY);const large=Array.from({length:16},(_,index)=>({...structuredClone(plan),id:`plan-${index}`,events:Array.from({length:100},(_,j)=>({id:`event-${index}-${j}`,at:'2026-10-02T04:00:00Z',decision:'continue' as const,note:'字'.repeat(2000),review:null}))}));expect(()=>persistPlans(saved,large)).toThrow(/容量上限/);expect(localStorage.getItem(PLAN_STORAGE_KEY)).toBe(original);expect(loadPlans().state.plans).toHaveLength(1);});
 it('preserves corrupt storage and blocks stale-tab overwrite',async()=>{const {s,criteria,candidate}=await analysis();const plan=createPlan(s,candidate,criteria,'本地记录');const empty=loadPlans().state;const saved=persistPlans(empty,[plan]);expect(saved.plans).toHaveLength(1);expect(()=>persistPlans(empty,[])).toThrow(/另一个页面/);localStorage.setItem(PLAN_STORAGE_KEY,'broken');expect(loadPlans().error).not.toBeNull();expect(()=>persistPlans(saved,[])).toThrow();expect(localStorage.getItem(PLAN_STORAGE_KEY)).toBe('broken');});
});
